name: TestCommands
version: '1.0-SNAPSHOT'
main: me.rokasrgb.testCommands.TestCommands
api-version: '1.21'

commands:
  heal:
    description: Heals the player to max health
    usage: /heal
    permission:

  feed:
    description: Feed the player
    usage: /feed

  fly:
    description: Allows the player to fly
    usage: /fly

permissions:
  permissions.fly:
    description: To get it you have to kill the Ender dragon
    default: false

  permissions.feed:
    description: To get it you have to get "A balanced diet"
    default: false

  permissions.heal:
    description: To get it you have to kill the Wither

depend: [LuckPerms]